#!/bin/bash

sudo -u root yum -y -q install httpd

sudo -u root touch /var/www/html/index.html
sudo /bin/su -c \"echo 'Welcome to FoggyKitchen.com! This is WEBSERVER...' > /var/www/html/index.html\"

sudo -u root service firewalld stop
sudo -u root service httpd start

